In [1]:
import tensorflow as tf
tf.debugging.set_log_device_placement(True)

In [2]:
with tf.device("GPU:0"):
    a = tf.constant([0.0, 1.0, 2.0])

In [3]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [4]:
del(a)

In [5]:
ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=False)
ta = ta.write(0, 1.0)
ta = ta.write(1, 2.0)
ta = ta.write(2, 3.0)

In [8]:
#tf.debugging.set_log_device_placement(True)

# Create some tensors
a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
c = tf.matmul(a, b)

print(c)


Executing op MatMul in device /job:localhost/replica:0/task:0/device:GPU:0
tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [9]:
for i in [a, b, c]:
    print(i.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:GPU:0


In [10]:
# Create some tensors
s = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
e = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
w = tf.matmul(a, b)

In [11]:
w

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>